apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-app-set
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/Tom-HA/k8s-operators-workshop.git
      revision: refactor-doc-and-pg-auth
      files:
      - path: "apps/infra/**/app-config.yaml"
  template:
    metadata:
      name: '{{chart}}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/Tom-HA/k8s-operators-workshop.git
          targetRevision: refactor-doc-and-pg-auth
          ref: deployRepo
        - repoURL: '{{repoURL}}'
          targetRevision: '{{targetRevision}}'
          chart: '{{chart}}'
          helm:
            valueFiles:
              - $deployRepo/apps/infra/{{path.basename}}/values.yaml
      destination:
        name: in-cluster
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
