apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services-app-set
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/Tom-HA/k8s-operators-workshop.git # change this to your repo URL
      revision: refactor-doc-and-pg-auth
      files:
      - path: "apps/services/**/app-config.yaml"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/Tom-HA/k8s-operators-workshop.git # change this to your repo URL
          targetRevision: '{{targetRevision}}'
          ref: deployRepo
        - repoURL: https://github.com/Tom-HA/k8s-operators-workshop.git # change this to your repo URL
          targetRevision: '{{targetRevision}}'
          path: "apps/services/{{path.basename}}/hooks"
        - repoURL: '{{repoURL}}'
          targetRevision: '{{targetRevision}}'
          path: '{{chartPath}}'
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - $deployRepo/apps/services/{{path.basename}}/values.yaml
      destination:
        name: in-cluster
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
