apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-labs-exercise
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/Tom-HA/k8s-operators-workshop.git # change this to your repo URL
      targetRevision: init-setup
      ref: deployRepo
    - repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 12.5.8
      chart: postgresql
      helm:
        valueFiles:
          - $deployRepo/apps/postgres/values.yaml
  destination:
    name: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true