name: Build Container Image

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  workflow_dispatch:

  pull_request:
    branches: 
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Container Build and Publish
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Set variables
        id: vars
        shell: bash
        run: |
          export repo_slug=$(echo ${GITHUB_REPOSITORY,,})
          echo "REPO_SLUG=${repo_slug}" >> $GITHUB_ENV
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.REPO_SLUG }}
          tags: |
            type=raw,value={{base_ref}}-{{sha}}
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: sample-pg-app/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_SLUG }}:build-cache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_SLUG }}:build-cache,mode=max